### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by liatula54** [soarsmu/SA4SE#1]
I would like to install dependencies for github.py script but couldn't find any instructions in the README.
Can you provide such instructions?
Thanks.

**Comment by happygirlzt** [comment]
Thank you for your interest in our work! However, it has been almost two years. I’m really sorry, I forgot to export the `environment.yml` back that time. I lost the environment setting already. May I suggest you just simply try to run `gitHub.py`? I guess it would print some uninstalled package error, you can then install those packages. There is certainly an issue is the package version is unknown. I checked HuggingFace website https://pypi.org/project/transformers/#history, based on the datetime, I suggest you try to install `transformers==2.10.0` Sorry for the inconvenience caused. Please let me know if you have further questions.
