### ISSUE TITLE
Source Code SentiStrength-SE

### ISSUE THREAD

**Issue by ghost** [soarsmu/SA4SE#2]
Hello, 

My name is Rayam Fonsêca, Master's student at the Federal University of Sergipe / Brazil. My research is based on sentiment analysis, I would like to know if there is a source code available from the SentiStrength-SE Project for student purposes.

**Comment by happygirlzt** [comment]
Hi,
Thank you for your interest in our work. I suggest contacting the authors of SentiStrength-SE to ask for the availability of the source code.
